### ISSUE TITLE
Taskt server Deployment 

### ISSUE THREAD

**Issue by junaid2314** [saucepleez/tasktServer#11]
Hi 
  i want to deploy taskt server version on window 10 . can you please add some guid line or step of deployment of taskt server and how to run and test?

**Comment by saucepleez** [comment]
Hi, please take a look at:

https://github.com/saucepleez/tasktServer/wiki/Sample-tasktServer-Deployment-using-IIS

You can mostly follow this guide, you will need to turn on IIS for Windows 10 in the 'Add Features' Option.
