### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by andreyofficinal** [saucepleez/tasktServer#2]
Hello @saucepleez!
Could you write some order of actions that needed to set up this server on a machine?
I am trying to start this site on a machine with Windows Server 2016, IIS 10 and Microsoft SQL Server.
After just copying and launching your solution, the error is
![image](https://user-images.githubusercontent.com/44296913/48359926-16252b00-e6af-11e8-83da-5aa43a258d76.png)
After some manipulations, error became 
![image](https://user-images.githubusercontent.com/44296913/48359966-29d09180-e6af-11e8-908b-b397380f7a04.png)
that means that I am trying to access right page(probably), but the config file is incorrect. After some manipulations with config file, the View pages are still unavailable. Could you provide some example of working config file? Are there some packages or tools that need to be installed before solution can run? Could you list some steps that necessary to set the solution up?

**Comment by saucepleez** [comment]
Hi,

I have not been working much on this project but I have pushed the latest from what I do have.  The latest master version here should be compatible with the current DEV version of taskt.  Try spinning that up and see how it goes - this solution has been tested mainly from running taskt clients and taskt server from localhost (same box). 

Once this project becomes more stable, I will create the instructions on how to bring up the application. I need to get an IIS box to start testing for that.

The general instructions should be:
- Run the script to create the database (**tasktserver-db-script.sql** from the repo)
- Open Solution and Edit **tasktServerContext.cs** to reflect the appropriate database connection, ex:
`  optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=tasktserver;Trusted_Connection=True;");`
- Start IISExpress

To connect clients, see:
https://github.com/saucepleez/tasktServer/wiki/Connecting-Clients

Lastly, for any errors please include the error codes as .txt files or translate them to english.

**Comment by andreyofficinal** [comment]
Hello @saucepleez!
I have performed the actions you listed, but I think there is no use because my problem has another reasons. The shown message didn't change, so I think the problem is earlier than connection to the database.
The text of error now

> Server Error in '/' Application.
> 
> This type of page is not served.
> 
> Description: The type of page you have requested is not served because it has been explicitly forbidden. The extension '.cshtml' may be incorrect. Please review the URL below and make sure that it is spelled correctly.
> 
> Requested URL: /Views/Home/index.cshtml
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1586.0

I think  the config is wrong.
My config is
[web.config.txt](https://github.com/saucepleez/tasktServer/files/2577269/web.config.txt)
Excuse my uncomprehending, but I don't understand how to correct it.

**Comment by saucepleez** [comment]
Closing issue as we are moving project to new architecture
